---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
        - name: springboot-app
          image: 273725063969.dkr.ecr.us-west-2.amazonaws.com/springboot-app:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "10Mi"
              cpu: "10m"
            limits:
              memory: "100Mi"
              cpu: "100m"    
